export const productos = [
  {
    id: 1,
    title: "Collar Zafiro",
    price: 2000,
    stock: 5,
    description: "Collar realizado en Piedras Simil preciosa Color Zafiro, largo regulable",
    category: "Casual",
    img: "https://res.cloudinary.com/ds1zblpny/image/upload/v1675946981/Mis%20Imagenes/5_y9xeqs.jpg",
  },
  {
    id: 2,
    title: "Collar Aqua",
    price: 2000,
    stock: 5,
    description: "Collar realizado en Piedras Simil preciosa Color Agua Marina, largo regulable",
    category: "Fiesta",
    img: "https://res.cloudinary.com/ds1zblpny/image/upload/v1675946981/Mis%20Imagenes/6_stimvx.jpg",
  },
  {
    id: 3,
    title: "Collar Azabache",
    price: 1500,
    stock: 5,
    description: "Collar realizado en Piedras Simil preciosa Color Negro Azabache con tintes verdes, largo regulable",
    category: "Fiesta",
    img: "https://res.cloudinary.com/ds1zblpny/image/upload/v1675946981/Mis%20Imagenes/7_mx14ck.jpg",
  },
  {
    id: 4,
    title: "Aros Esmeralda Largos",
    price: 3500,
    stock: 5,
    description: "Aros largos realizados en Piedras Simil preciosa Color Verde Esmeralda",
    category: "Fiesta",
    img: "https://res.cloudinary.com/ds1zblpny/image/upload/v1675946981/Mis%20Imagenes/8_fgy5ey.jpg",
  },
  {
    id: 5,
    title: "Aros Azabache Corto",
    price: 1500,
    stock: 5,
    description: "Aros cortos realizados en Piedras Simil preciosa Color Negro Azabache",
    category: "Fiesta",
    img: "https://res.cloudinary.com/ds1zblpny/image/upload/v1675946981/Mis%20Imagenes/9_jwsqs7.jpg",
  },
  {
    id: 6,
    title: "Aros Rojo Furia",
    price: 3500,
    stock: 5,
    description: "Aros largos realizados en Piedras Simil preciosa Color Rojo",
    category: "Fiesta",
    img: "https://res.cloudinary.com/ds1zblpny/image/upload/v1675946981/Mis%20Imagenes/10_kvd6xv.jpg",
  },
  {
    id: 7,
    title: "Aros Dorados Cortos",
    price: 2500,
    stock: 5,
    description: "Aros cortos realizados en Piedras Simil preciosa Color Dorado y cobre",
    category: "Fiesta",
    img: "https://res.cloudinary.com/ds1zblpny/image/upload/v1675946982/Mis%20Imagenes/11_vozj5n.jpg",
  },
  {
    id: 8,
    title: "Aros Esmeralda Cortos",
    price: 2500,
    stock: 5,
    description: "Aros cortos realizados en Piedras Simil preciosa Color Verde y negro",
    category: "Fiesta",
    img: "https://res.cloudinary.com/ds1zblpny/image/upload/v1675946982/Mis%20Imagenes/12_mrayxg.jpg",
  },


]

